services:
  web:
    build: .
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi-redis-app.rule=Host(`visitors.miikat.dev`)"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
